apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
data:
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
  WEBUI_PORT: "8080"
  VPN_ENABLED: "yes"
  LAN_NETWORK: "192.168.1.0/24"
  NAME_SERVERS: "8.8.8.8,8.8.4.4"
  KUBERNETES_ENABLED: "yes"
  POD_NETWORK: "10.244.0.0/16"
  SVC_NETWORK: "10.96.0.0/16"