apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
data:
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
  VPN_ENABLED: "yes"
  LAN_CIDR: "192.168.1.0/24"
  NAME_SERVERS: "8.8.8.8,8.8.4.4"
  K8S_CLUSTER: "yes"
  K8S_POD_CIDR: "10.244.0.0/16"
  K8S_SVC_CIDR: "10.96.0.0/16"